name: Gradle Build #

on:
  push:
    branches:
      - main # Trigger on push events to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request events targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Run on a fresh virtual machine

    steps:
      - uses: actions/checkout@v4 # Check out the repository code

      - name: Set up JDK 17 # Use the setup-java action to configure the JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto' # e.g., Amazon Corretto
          cache: 'gradle' # Cache Gradle dependencies to speed up builds

      - name: Validate Gradle wrapper # Recommended action for security
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle # Use the setup-gradle action
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle # Execute the build and test tasks using the Gradle wrapper
        run: chmod +x ./gradlew 
             ./gradlew build
